//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Xml.Serialization;
// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class TO {
    private TestGroup[] tgField;
    private string folderField;
    private string descriptionField;

    [System.Xml.Serialization.XmlElementAttribute("TG", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TestGroup[] TG {
        get { return this.tgField; }
        set { this.tgField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Folder {
        get { return this.folderField; }
        set { this.folderField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get { return this.descriptionField; }
        set { this.descriptionField = value; }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class TestGroup {
    private object[] itemsField;
    private string classField;
    private string descriptionField;
    private bool cancelIfFailField;
    private bool independentField;

    [System.Xml.Serialization.XmlElementAttribute("MC", typeof(MethodCustom), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("MI", typeof(MethodInterval), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("MP", typeof(MethodProcess), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("MT", typeof(MethodTextual), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items {
        get { return this.itemsField; }
        set { this.itemsField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Class {
        get { return this.classField; }
        set { this.classField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get { return this.descriptionField; }
        set { this.descriptionField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool CancelIfFail {
        get { return this.cancelIfFailField; }
        set { this.cancelIfFailField = value; }
    }


    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Independent {
        get { return this.independentField; }
        set { this.independentField = value; }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MethodCustom {
    private MethodCustomParameter[] parameterField;
    private string methodField;
    private string descriptionField;
    private bool cancelIfFailField;

    [System.Xml.Serialization.XmlElementAttribute("Parameter", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public MethodCustomParameter[] Parameter {
        get { return this.parameterField; }
        set { this.parameterField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Method {
        get { return this.methodField; }
        set { this.methodField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get { return this.descriptionField;}
        set { this.descriptionField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool CancelIfFail {
        get { return this.cancelIfFailField; }
        set { this.cancelIfFailField = value; }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class MethodCustomParameter {
    private string keyField;
    private string valueField;

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Key {
        get { return this.keyField; }
        set { this.keyField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value {
        get { return this.valueField; }
        set { this.valueField = value; }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MethodTextual {
    private string methodField;
    private string descriptionField;
    private bool cancelIfFailField;
    private string textField;

    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Method {
        get { return this.methodField; }
        set { this.methodField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get { return this.descriptionField; }
        set { this.descriptionField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool CancelIfFail {
        get { return this.cancelIfFailField; }
        set { this.cancelIfFailField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Text {
        get { return this.textField; }
        set { this.textField = value; }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MethodProcess {
    private string methodField;
    private string descriptionField;
    private bool cancelIfFailField;
    private string pathField;
    private string executableField;
    private string parametersField;
    private string expectedField;

    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Method {
        get { return this.methodField; }
        set { this.methodField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get { return this.descriptionField; }
        set { this.descriptionField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool CancelIfFail {
        get { return this.cancelIfFailField; }
        set { this.cancelIfFailField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Path {
        get { return this.pathField; }
        set { this.pathField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Executable {
        get { return this.executableField; }
        set { this.executableField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Parameters {
        get { return this.parametersField; }
        set { this.parametersField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Expected {
        get { return this.expectedField; }
        set { this.expectedField = value; }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class MethodInterval {
    private MethodIntervalLowComparator lowComparatorField;
    private string methodField;
    private string descriptionField;
    private bool cancelIfFailField;
    private double lowField;
    private double highField;
    private MethodIntervalHighComparator highComparatorField;
    private string fdField;
    private MethodIntervalPrefix prefixField;
    private MethodIntervalUnits unitsField;
    private MethodIntervalVA_Descriptor vA_DescriptorField;
    private bool vA_DescriptorFieldSpecified;

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MethodIntervalLowComparator LowComparator {
        get { return this.lowComparatorField; }
        set { this.lowComparatorField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "ID")]
    public string Method {
        get { return this.methodField; }
        set { this.methodField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Description {
        get { return this.descriptionField; }
        set { this.descriptionField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool CancelIfFail {
        get { return this.cancelIfFailField; }
        set { this.cancelIfFailField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double Low {
        get { return this.lowField; }
        set { this.lowField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public double High {
        get { return this.highField; }
        set { this.highField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MethodIntervalHighComparator HighComparator {
        get { return this.highComparatorField; }
        set { this.highComparatorField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute(DataType = "nonNegativeInteger")]
    public string FD {
        get { return this.fdField; }
        set { this.fdField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MethodIntervalPrefix Prefix {
        get { return this.prefixField; }
        set { this.prefixField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MethodIntervalUnits Units {
        get { return this.unitsField; }
        set { this.unitsField = value; }
    }

    [System.Xml.Serialization.XmlAttributeAttribute()]
    public MethodIntervalVA_Descriptor VA_Descriptor {
        get { return this.vA_DescriptorField; }
        set { this.vA_DescriptorField = value; }
    }

    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool VA_DescriptorSpecified {
        get { return this.vA_DescriptorFieldSpecified; }
        set { this.vA_DescriptorFieldSpecified = value; }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum MethodIntervalLowComparator {
    GE,
    GT,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum MethodIntervalHighComparator {
    LE,
    LT,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum MethodIntervalPrefix {
    peta,
    tera,
    giga,
    mega,
    kilo,
    hecto,
    deca,
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    deci,
    centi,
    milli,
    micro,
    nano,
    pico,
    femto,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum MethodIntervalUnits {
    [System.Xml.Serialization.XmlEnumAttribute("")]
    Item,
    Amperes,
    [System.Xml.Serialization.XmlEnumAttribute("°Celcius")]
    Celcius,
    Farads,
    Henries,
    Hertz,
    Ohms,
    Seconds,
    Siemens,
    Volts,
    VoltAmperes,
    Watts,
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public enum MethodIntervalVA_Descriptor {
    AC,
    DC,
    Peak,
    PP,
    RMS,
}
