//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Diagnostics;
using static TestSequencer.MethodAssertions;

namespace T10 {


    internal class Class1 {

        static string Method1() {
            Debug.Assert(MethodTextual(
            Description: "Verify Firmware Revision Text.",
            CancelIfFail: "true",
            Text: "7.10"));

        }

        static string Method2() {
            Debug.Assert(MethodCustom(
            Description: "Custom Power Method.",
            CancelIfFail: "true",
            "Key=Volts DC, Value=5V ± 5%",
            "Key=Watts DC, Value=7.5375 ± 15%"));

        }

        static string Method3() {
            Debug.Assert(MethodProcess(
            Description: "Programming Process.",
            CancelIfFail: "true",
            Path: "C:\\Program Files\\Microchip\\MPLABX\\v6.15\\mplab_platform\\mplab_ipe",
            Executable: "ipecmd.exe",
            Parameters: "/P12LF1552 /E /M /Y /TPPK4 /F\"C:\\Firmware\\U1.hex\"",
            Expected: "0"));

        }

        static string Method4() {
            Debug.Assert(MethodInterval(
            Description: "Miscellaneous Interval Measurement.",
            CancelIfFail: "true",
            LowComparator: "GT",
            Low: "1.5",
            High: "2.5",
            HighComparator: "LE",
            FractionalDigits: "2",
            UnitPrefix: "NONE",
            Units: "NONE",
            UnitSuffix: "NONE"));

        }
    }

    internal class Class2 {

        static string Method5() {
            Debug.Assert(MethodCustom(
            Description: "Custom Power Method.",
            CancelIfFail: "true",
            "Key=Volts DC, Value=5 ± 5%",
            "Key=Watts DC, Value=7.5375 ± 15%"));

        }

        static string Method6() {
            Debug.Assert(MethodInterval(
            Description: "+5VDC Interval Measurement.",
            CancelIfFail: "true",
            LowComparator: "GE",
            Low: "4.75",
            High: "5.25",
            HighComparator: "LE",
            FractionalDigits: "3",
            UnitPrefix: "kilo",
            Units: "Volts",
            UnitSuffix: "DC"));

        }

        static string Method7() {
            Debug.Assert(MethodProcess(
            Description: "Programming Process.",
            CancelIfFail: "true",
            Path: "C:\\Program Files\\Microchip\\MPLABX\\v6.15\\mplab_platform\\mplab_ipe",
            Executable: "ipecmd.exe",
            Parameters: "/P12LF1552 /E /M /Y /TPPK4 /F\"C:\\Firmware\\U2.hex\"",
            Expected: "0"));

        }

        static string Method8() {
            Debug.Assert(MethodTextual(
            Description: "Verify Firmware Revision Text.",
            CancelIfFail: "false",
            Text: "5.29"));

        }
    }
}
